fix: normalizeCredential overwrites "evidence" when "vc" is missing
decentralized-identity/did-jwt-vc pull request #86
Opened 2021-07-30 00:42 UTC by joshbax189

Occurs when calling `normalizeCredential` with an argument of type `VerifiableCredential` (i.e. has `credentialSubject` instead of `vc`).

For example
```
{
  credentialSubject: {
    id: 'did:example:ebfeb1f712ebc6f1c276e12ec21',
  },
    evidence: {
      foo: 'bar',
    },
 }
 ```
 after normalization becomes
 ```
{
  credentialSubject: {
    id: 'did:example:ebfeb1f712ebc6f1c276e12ec21',
  },
    evidence: undefined
 }
 ```

2021-08-04 11:25 UTC, mirceanis approved these changes
Thank you for the contribution. It looks great!

I think it would be wise to also add the symmetrical operation when transforming from W3C JSON to JWT payload.
Do you think you can add that to this PR as well?

2021-08-08 08:35 UTC, joshbax189 commented
Good observation! I actually fixed the W3C -> JWT transform in PR #78 but didn't fix this direction (JWT -> W3C). 

Taken together the changes should move `['evidence', 'termsOfUse', 'refreshService', 'credentialSchema', 'credentialStatus']` into the `vc` object for the W3C -> JWT transform, and back to the top level in the JWT -> W3C transform, _unless_ those props already exist in the input.

2021-08-10 16:32 UTC, mirceanis commented
> Taken together the changes should move ['evidence', 'termsOfUse', 'refreshService', 'credentialSchema', 'credentialStatus'] into the vc object for the W3C -> JWT transform, and back to the top level in the JWT -> W3C transform

yes, that's the general idea

> unless those props already exist in the input.

For the moment, this should hold true. In a future version, there should not be any ambiguity here. Either an error should be thrown or the existing props overridden. (#64)

2021-11-10 18:49 UTC, mirceanis requested changes
It would be great to have the [symmetric transformation](https://github.com/decentralized-identity/did-jwt-vc/pull/86#pullrequestreview-722165819) included here as well.

Do you think you can add them?

2021-11-17 01:22 UTC, joshbax189 commented
Hey sorry @mirceanis I think I explained myself poorly (and then forgot to clear it up!).

Commit 1284973 inside #78 already implements the fix within `transformCredentialInput` function, which produces `JwtCredentialPayload`. This PR just copies the same pattern to `normalizeJwtCredentialPayload` (which is called by `normalizeCredential`, transforming JWT to W3C).

Can you double check the test cases in `converters.tests.ts` under "other W3C fields" sections do what you expect? There should be one section for each of `transformCredentialInput` and `normalizeCredential`.

2021-11-17 09:28 UTC, mirceanis commented
I see. My bad for not looking thoroughly enough 😅
I'll take another look and merge it in if all is good.
Thanks for contributing!

2021-11-23 09:41 UTC, mirceanis approved these changes
looks great, thank you for the contribution!

2021-11-23 09:42 UTC, merged